
<h1 id="0.-Import-libraries">0. Import libraries<a class="anchor-link" href="#0.-Import-libraries">¶</a></h1>


In [1]:

import numpy as np
import pandas as pd




<h1 id="1.-데이터-적재">1. 데이터 적재<a class="anchor-link" href="#1.-데이터-적재">¶</a></h1><h2 id="sepal:-꽃받침,-petal:-꽃잎">sepal: 꽃받침, petal: 꽃잎<a class="anchor-link" href="#sepal:-꽃받침,-petal:-꽃잎">¶</a></h2>


In [2]:

from sklearn.datasets import load_iris
iris_dataset = load_iris()



In [4]:

print("iris_dataset size:\n", iris_dataset.keys())


iris_dataset size:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [6]:

print(iris_dataset['DESCR'][:193] + "\n...")


Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [8]:

print("name of target:", iris_dataset['target_names'])
print("name of feature:", iris_dataset['feature_names'])
print("type of data", type(iris_dataset['data']))
print("shape of data", iris_dataset['data'].shape)
print("first five rows of data\n",iris_dataset['data'][:5])
print("type of target", type(iris_dataset['target']))
print("size of target", iris_dataset['target'].shape)
print("target:", iris_dataset['target'])



name of target: ['setosa' 'versicolor' 'virginica']
name of feature: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
type of data <class 'numpy.ndarray'>
shape of data (150, 4)
first five rows of data
 [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
type of target <class 'numpy.ndarray'>
size of target (150,)
target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]



<h1 id="2.-성과-측정:-훈련-데이터(Train-data)와-테스트-데이터(Test-data)">2. 성과 측정: 훈련 데이터(Train data)와 테스트 데이터(Test data)<a class="anchor-link" href="#2.-성과-측정:-훈련-데이터(Train-data)와-테스트-데이터(Test-data)">¶</a></h1>


In [9]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_dataset['data'],
                                                    iris_dataset['target'],random_state=0)



In [17]:

print("size of X_train:", x_train.shape) #(# of data * 75%, # of features)
print("size of y_train:", y_train.shape) #(# of data * 75%)


size of X_train: (112, 4)
size of y_train: (112,)


In [18]:

print("size of x_test:", x_test.shape)
print("size of y_test:", y_test.shape)

size of x_test: (38, 4)
size of y_test: (38,)



<h1 id="3.-가장-먼저-할-일:-데이터-살펴보기">3. 가장 먼저 할 일: 데이터 살펴보기<a class="anchor-link" href="#3.-가장-먼저-할-일:-데이터-살펴보기">¶</a></h1>


In [19]:

iris_dataframe = pd.DataFrame(x_train, columns = iris_dataset.feature_names)
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15,15),marker='o',
                          hist_kwds={'bins':20},s=60, alpha=.8)



array([[<matplotlib.axes._subplots.AxesSubplot object at 0x000001A8366355C0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x000001A836D76908>]], dtype=object)


<h1 id="4.-첫-번째-머신러닝-모델:-k-최근접-이웃-알고리즘">4. 첫 번째 머신러닝 모델: k-최근접 이웃 알고리즘<a class="anchor-link" href="#4.-첫-번째-머신러닝-모델:-k-최근접-이웃-알고리즘">¶</a></h1>


In [20]:

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)



In [21]:

knn.fit(x_train, y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


<h1 id="5.-예측하기">5. 예측하기<a class="anchor-link" href="#5.-예측하기">¶</a></h1>


In [23]:

x_new = np.array([[5,2.9,1,0.2]])
print("x_new.shape:", x_new.shape)



x_new.shape: (1, 4)


In [24]:

prediction = knn.predict(x_new)
print("prediction:",prediction)
print("predicted target name:",iris_dataset['target_names'][prediction])



prediction: [0]
predicted target name: ['setosa']



<h1 id="6.-모델-평가하기">6. 모델 평가하기<a class="anchor-link" href="#6.-모델-평가하기">¶</a></h1>


In [25]:

y_pred = knn.predict(x_test)
print("predicted test dataset:\n", y_pred)



predicted test dataset:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [26]:

print("accuracy for test set: {:.2f}".format(np.mean(y_pred==y_test)))



accuracy for test set: 0.97
